<!DOCTYPE html>
<html>
<head>
    <title>Books</title>
    <link rel="stylesheet" href="/css/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
<h1>${book.name}</h1>
<p>Author: ${book.author}</p>
<p>Genre: ${book.genre}</p>

<a href="/">Return to main paige</a>
</body>
</html>